vich_uploader:
    db_driver: orm

    mappings:
        recipe_images:
            uri_prefix: /images/EcritsLyndia
            upload_destination: '%kernel.project_dir%/public/images/EcritsLyndia'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
